version: "3.8"

services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_USER: liteblog
            POSTGRES_PASSWORD: superpassword
            POSTGRES_DB: liteblog
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
